Module3 task1
htmlacademy-adaptive/99239-cat-energy-22 pull request #5
Opened 2021-04-15 19:30 UTC by tsyganovp

2021-04-17 10:00 UTC, nikopol-fw requested changes

2021-04-18 05:47 UTC, tsyganovp commented on source/index.html
> +          height="280"
Исправил

2021-04-18 07:03 UTC, tsyganovp commented on source/sass/blocks/articles.scss
> +      line-height: 37px;
Везде сделал

2021-04-22 10:37 UTC, nikopol-fw approved these changes

2021-04-22 10:37 UTC, merged