Module3 task2
htmlacademy-adaptive/99239-cat-energy-22 pull request #6
Opened 2021-04-22 12:13 UTC by tsyganovp

2021-04-24 12:01 UTC, nikopol-fw requested changes

2021-04-24 12:01 UTC, nikopol-fw commented on source/sass/blocks/addition.scss
> +}
Для всех fieldset'ов в форме завести общий класс, для заголовков (legend) точно также. Все общие стили связанные с оформлением перенести на эти классы.

У тебя много повторяющегося кода, для каждого fieldset заводишь новые классы, и в них пишешь те же стили. А на самом деле они очень похожи.

Следует пересмотреть подход

2021-04-24 18:18 UTC, tsyganovp commented on source/sass/blocks/academy-block.scss
>    line-height: (18 / 16);
Не понял

2021-04-25 18:53 UTC, nikopol-fw approved these changes

2021-04-25 19:17 UTC, merged